version: '3.7'

services:
  ubuntu20-osquery:
    image: "dactiv/osquery:4.5.1-ubuntu20.04"
    volumes:
      - ./fleet.crt:/etc/osquery/fleet.crt
      - ./example_osquery.flags:/etc/osquery/osquery.flags
    environment:
      ENROLL_SECRET: "${ENROLL_SECRET:?ENROLL_SECRET must be set for server authentication}"
    command: osqueryd --flagfile=/etc/osquery/osquery.flags --tls_hostname=${FLEET_SERVER-host.docker.internal:8412}
    ulimits:
      core:
        hard:  1000000000
        soft:  1000000000

  ubuntu18-osquery:
    image: "dactiv/osquery:4.5.1-ubuntu18.04"
    volumes:
      - ./fleet.crt:/etc/osquery/fleet.crt
      - ./example_osquery.flags:/etc/osquery/osquery.flags
    environment:
      ENROLL_SECRET: "${ENROLL_SECRET:?ENROLL_SECRET must be set for server authentication}"
    command: osqueryd --flagfile=/etc/osquery/osquery.flags --tls_hostname=${FLEET_SERVER-host.docker.internal:8412}
    ulimits:
      core:
        hard:  1000000000
        soft:  1000000000

  ubuntu16-osquery:
    image: "dactiv/osquery:4.5.1-ubuntu16.04"
    volumes:
      - ./fleet.crt:/etc/osquery/fleet.crt
      - ./example_osquery.flags:/etc/osquery/osquery.flags
    environment:
      ENROLL_SECRET: "${ENROLL_SECRET:?ENROLL_SECRET must be set for server authentication}"
    command: osqueryd --flagfile=/etc/osquery/osquery.flags --tls_hostname=${FLEET_SERVER-host.docker.internal:8412}
    ulimits:
      core:
        hard:  1000000000
        soft:  1000000000

  ubuntu14-osquery:
    image: "dactiv/osquery:4.5.1-ubuntu14.04"
    volumes:
      - ./fleet.crt:/etc/osquery/fleet.crt
      - ./example_osquery.flags:/etc/osquery/osquery.flags
    environment:
      ENROLL_SECRET: "${ENROLL_SECRET:?ENROLL_SECRET must be set for server authentication}"
    command: osqueryd --flagfile=/etc/osquery/osquery.flags --tls_hostname=${FLEET_SERVER-host.docker.internal:8412}
    ulimits:
      core:
        hard:  1000000000
        soft:  1000000000

  centos8-osquery:
    image: "dactiv/osquery:4.5.1-centos8"
    volumes:
      - ./fleet.crt:/etc/osquery/fleet.crt
      - ./example_osquery.flags:/etc/osquery/osquery.flags
    environment:
      ENROLL_SECRET: "${ENROLL_SECRET:?ENROLL_SECRET must be set for server authentication}"
    command: osqueryd --flagfile=/etc/osquery/osquery.flags --tls_hostname=${FLEET_SERVER-host.docker.internal:8412}
    ulimits:
      core:
        hard:  1000000000
        soft:  1000000000

  centos7-osquery:
    image: "dactiv/osquery:4.5.1-centos7"
    volumes:
      - ./fleet.crt:/etc/osquery/fleet.crt
      - ./example_osquery.flags:/etc/osquery/osquery.flags
    environment:
      ENROLL_SECRET: "${ENROLL_SECRET:?ENROLL_SECRET must be set for server authentication}"
    command: osqueryd --flagfile=/etc/osquery/osquery.flags --tls_hostname=${FLEET_SERVER-host.docker.internal:8412}
    ulimits:
      core:
        hard:  1000000000
        soft:  1000000000

  centos6-osquery:
    image: "dactiv/osquery:4.5.1-centos6"
    volumes:
      - ./fleet.crt:/etc/osquery/fleet.crt
      - ./example_osquery.flags:/etc/osquery/osquery.flags
    environment:
      ENROLL_SECRET: "${ENROLL_SECRET:?ENROLL_SECRET must be set for server authentication}"
    command: osqueryd --flagfile=/etc/osquery/osquery.flags --tls_hostname=${FLEET_SERVER-host.docker.internal:8412}
    ulimits:
      core:
        hard:  1000000000
        soft:  1000000000
