version: '3.7'

networks:
  fleet-preview:
    name: fleet-preview
    external: true

services:
  ubuntu20-osquery:
    image: "osquery/osquery:4.6.0-ubuntu20.04"
    volumes:
      - ./fleet.crt:/etc/osquery/fleet.crt
      - ./example_osquery.flags:/etc/osquery/osquery.flags
      - ./uuids/ubuntu20-osquery:/sys/class/dmi/id/product_uuid
    environment:
      ENROLL_SECRET: "${ENROLL_SECRET:?ENROLL_SECRET must be set for server authentication}"
    command: osqueryd --flagfile=/etc/osquery/osquery.flags --tls_hostname=${FLEET_SERVER-host.docker.internal:8412}
    ulimits:
      core:
        hard:  1000000000
        soft:  1000000000
    networks:
      - fleet-preview

  ubuntu18-osquery:
    image: "osquery/osquery:4.6.0-ubuntu18.04"
    volumes:
      - ./fleet.crt:/etc/osquery/fleet.crt
      - ./example_osquery.flags:/etc/osquery/osquery.flags
      - ./uuids/ubuntu18-osquery:/sys/class/dmi/id/product_uuid
    environment:
      ENROLL_SECRET: "${ENROLL_SECRET:?ENROLL_SECRET must be set for server authentication}"
    command: osqueryd --flagfile=/etc/osquery/osquery.flags --tls_hostname=${FLEET_SERVER-host.docker.internal:8412}
    ulimits:
      core:
        hard:  1000000000
        soft:  1000000000
    networks:
      - fleet-preview

  ubuntu16-osquery:
    image: "osquery/osquery:4.6.0-ubuntu16.04"
    volumes:
      - ./fleet.crt:/etc/osquery/fleet.crt
      - ./example_osquery.flags:/etc/osquery/osquery.flags
      - ./uuids/ubuntu16-osquery:/sys/class/dmi/id/product_uuid
    environment:
      ENROLL_SECRET: "${ENROLL_SECRET:?ENROLL_SECRET must be set for server authentication}"
    command: osqueryd --flagfile=/etc/osquery/osquery.flags --tls_hostname=${FLEET_SERVER-host.docker.internal:8412}
    ulimits:
      core:
        hard:  1000000000
        soft:  1000000000
    networks:
      - fleet-preview

  ubuntu14-osquery:
    image: "osquery/osquery:4.6.0-ubuntu14.04"
    volumes:
      - ./fleet.crt:/etc/osquery/fleet.crt
      - ./example_osquery.flags:/etc/osquery/osquery.flags
      - ./uuids/ubuntu14-osquery:/sys/class/dmi/id/product_uuid
    environment:
      ENROLL_SECRET: "${ENROLL_SECRET:?ENROLL_SECRET must be set for server authentication}"
    command: osqueryd --flagfile=/etc/osquery/osquery.flags --tls_hostname=${FLEET_SERVER-host.docker.internal:8412}
    ulimits:
      core:
        hard:  1000000000
        soft:  1000000000
    networks:
      - fleet-preview

  centos8-osquery:
    image: "osquery/osquery:4.6.0-centos8"
    volumes:
      - ./fleet.crt:/etc/osquery/fleet.crt
      - ./example_osquery.flags:/etc/osquery/osquery.flags
      - ./uuids/centos8-osquery:/sys/class/dmi/id/product_uuid
    environment:
      ENROLL_SECRET: "${ENROLL_SECRET:?ENROLL_SECRET must be set for server authentication}"
    command: osqueryd --flagfile=/etc/osquery/osquery.flags --tls_hostname=${FLEET_SERVER-host.docker.internal:8412}
    ulimits:
      core:
        hard:  1000000000
        soft:  1000000000
    networks:
      - fleet-preview

  centos7-osquery:
    image: "osquery/osquery:4.6.0-centos7"
    volumes:
      - ./fleet.crt:/etc/osquery/fleet.crt
      - ./example_osquery.flags:/etc/osquery/osquery.flags
      - ./uuids/centos7-osquery:/sys/class/dmi/id/product_uuid
    environment:
      ENROLL_SECRET: "${ENROLL_SECRET:?ENROLL_SECRET must be set for server authentication}"
    command: osqueryd --flagfile=/etc/osquery/osquery.flags --tls_hostname=${FLEET_SERVER-host.docker.internal:8412}
    ulimits:
      core:
        hard:  1000000000
        soft:  1000000000
    networks:
      - fleet-preview

  centos6-osquery:
    image: "osquery/osquery:4.6.0-centos6"
    volumes:
      - ./fleet.crt:/etc/osquery/fleet.crt
      - ./example_osquery.flags:/etc/osquery/osquery.flags
      - ./uuids/centos6-osquery:/sys/class/dmi/id/product_uuid
    environment:
      ENROLL_SECRET: "${ENROLL_SECRET:?ENROLL_SECRET must be set for server authentication}"
    command: osqueryd --flagfile=/etc/osquery/osquery.flags --tls_hostname=${FLEET_SERVER-host.docker.internal:8412}
    ulimits:
      core:
        hard:  1000000000
        soft:  1000000000
    networks:
      - fleet-preview
